name: har
channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python==3.6.8
- pytorch==1.0.0
- torchvision
- ipykernel>=4.6.1
- jupyter>=1.0.0
- pytest>=3.6.4
- scikit-learn>=0.19.1
- pip>=19.0.3
- pip:
  - ipywebrtc  
